services:
  - type: web
    name: sws-seizure-predictor
    runtime: python
    rootDir: backend
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODELS_DIR
        value: saved_models
    plan: free
